### PR TITLE
Feature article

### PR DESCRIPTION
**Pull request by deedima3**
## Overview

Issue id: #15 #16 #8 #5 #4 #2

Changes for all features related to article, adding some new feature newpost, and seearticle using SSG with revalidator

## Type of change

- [ ] Bug fix
- [x] Enhancement
- [x] New feature 
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## How Has This Been Tested?
- [ ] New unit tests added.
- [x] Manual tested.

## Checklist:
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by Jrhero14 — COMMENTED** [review]
Formating font paragraf H3 ya? Ganti pake "p/text" aja Dim

**Review by Jrhero14 — COMMENTED** [review]
Offside
image

**Review by Jrhero14 — COMMENTED** [review]
save articlenya belum ya?
image

**Comment by deedima3** [comment]
> Formating font paragraf H3 ya? Ganti pake "p/text" aja Dim

ini yang mana jer?

**Comment by Jrhero14** [comment]
yang ini
image

**Pull request merged**
